In [1]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

added_array = array + 2
print("Array after adding 2:", added_array)

multiplied_array = array * 3
print("Array after multiplying by 3:", multiplied_array)

divided_array = array / 2
print("Array after dividing by 2:", divided_array)

Array after adding 2: [3 4 5 6 7]
Array after multiplying by 3: [ 3  6  9 12 15]
Array after dividing by 2: [0.5 1.  1.5 2.  2.5]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

# Reversing
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

x = np.array([1,2,3,4,5,1,2,1,1,1])

#Most frequent value FOR X
unique, counts = np.unique(x, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]

# Indices of most frequent value
indices = np.where(x == most_frequent_value)[0]
print("Most frequent value in x:", most_frequent_value)
print("Indices:", indices)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

# Most frequent value FOR Y
unique, counts = np.unique(y, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]

# Indices of most frequent value
indices = np.where(y == most_frequent_value)[0]

print("Most frequent value in y:", most_frequent_value)
print("Indices:", indices)

Reversed array: [5 4 6 3 2 1]
Most frequent value in x: 1
Indices: [0 5 7 8 9]
Most frequent value in y: 1
Indices: [0 1 2]


In [3]:
import numpy as np

arr = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

element_a = arr[0, 1]
print("Element at 1st row and 2nd column:", element_a)

element_b = arr[2, 0]
print("Element at 3rd row and 1st column:", element_b)

Element at 1st row and 2nd column: 20
Element at 3rd row and 1st column: 70


In [4]:
import numpy as np

array = np.linspace(10, 100, 25)

print("Dimensions of the array:", array.ndim)
print("Shape of the array:", array.shape)
print("Total elements in the array:", array.size)
print("Data type of each element:", array.dtype)
print("Total number of bytes consumed by the array:", array.nbytes)

transposed_array_reshape = array.reshape(25, 1)
print("Transposed array using reshape():\n", transposed_array_reshape)

transposed_array_T = array.T
print("Transposed array using T attribute:\n", transposed_array_T)

Dimensions of the array: 1
Shape of the array: (25,)
Total elements in the array: 25
Data type of each element: float64
Total number of bytes consumed by the array: 200
Transposed array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed array using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [5]:
import numpy as np

array = np.array([[10, 20, 30, 40],
                  [50, 60, 70, 80],
                  [90, 15, 20, 35]])

mean_value = np.mean(array)
median_value = np.median(array)
max_value = np.max(array)
min_value = np.min(array)
unique_elements = np.unique(array)

print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique elements:", unique_elements)

reshaped_array = array.reshape(4, 3)
print("Reshaped array 4 rows, 3 columns:\n", reshaped_array)

resized_array = np.resize(array, (2, 3))
print("Resized array 2 rows, 3 columns:\n", resized_array)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array 4 rows, 3 columns:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array 2 rows, 3 columns:
 [[10 20 30]
 [40 50 60]]
